sylius_resource:
  resources:
    akki_sylius_localization_plugin.localized_entry:
      driver: doctrine/orm
      classes:
        model: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntry
        interface: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntryInterface
      translation:
        classes:
          model: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntryTranslation
          interface: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntryTranslationInterface
