parameters:
  akki_sylius_localization_plugin.model.localized_entry.validation_groups: ['sylius']
  akki_sylius_localization_plugin.model.localized_entry_translation.validation_groups: ['sylius']

sylius_resource:
  resources:
    akki_sylius_localization_plugin.localized_entry:
      driver: doctrine/orm
      classes:
        model: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntry
        repository: Akki\SyliusLocalizationPlugin\Repository\Localization\LocalizedEntryRepository
        interface: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntryInterface
        form: Akki\SyliusLocalizationPlugin\Form\Type\LocalizedEntryType
      translation:
        classes:
          model: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntryTranslation
          interface: Akki\SyliusLocalizationPlugin\Entity\Localization\LocalizedEntryTranslationInterface
          form: Akki\SyliusLocalizationPlugin\Form\Type\LocalizedEntryTranslationType
